name: complex
on: push
jobs:
  ubuntu: ubuntu-latest
    runs-on:
    steps:
      - run: date
  windows: windows-latest
    runs-on:
    steps:
      - run: date  
  macos: macos-latest
    runs-on:
    steps:
      - run: date  
  depends:
    needs: [ubuntu,windows,macos]
    runs-on: macos-latest
    steps:
      - run: date   
